services:
    database:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DB:-app}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123123}
            MYSQL_USER: ${MYSQL_USER:-app}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Root}
        ports:
            - "3306:3306"
        volumes:
            - database_data:/var/lib/mysql:rw

volumes:
    database_data:
